apiVersion: osg-htc.org/v1
kind: ComputeEntrypoint
metadata:
  name: chtc-spark-ce1
  namespace: osg-ce-dev
  annotation:
    topology/facility: CHTC
    topology/resource-group: CHTC-Spark 
    topology/resource: CHTC-Spark-CE1
    topology/sponsor: osg:100
    topology/contact: Jeff Dost
    topology/contact-email: jdost@ucsd.edu
    topology/site-city: Madison
    topology/site-country: US
    topology/site-latitude: 43.0711999
    topology/site-longitude: -89.4065713
    topology/production: true
    factory/entry-name: OSG_US_CHTC-Spark-CE1
    factory/glidein-site: CHTC-Spark
    factory/glidein-resource: CHTC-Spark-CE1
    gracc/site: CHTC
  labels:
    pool/ospool: true
    pool/igwn: false
    pool/atlas: false
    pool/dune: false
    pool/icecube: false
    pool/jlab: false
    pool/cms: false
    pool/gluex: false
spec:
  kubernetes:
    image: hub.opensciencegrid.org/osg-htc/hosted-ce:24-release
    hostname: chtc-spark-ce1.svc.opensciencegrid.org
    sleep: false
    replicas: 1
    node:
      hostname: null
      labels:
        datacenter: wid-vlan5
    service:
      annotations:
        metallb.universe.tf/address-pool: tiger-vlan5
  users:
  - user: osg01
    scitoken: https://scitokens.org/osg-connect
  - user: osg04
    scitoken: https://cms-auth.web.cern.ch/,bad55f4e-602c-4e8d-a5c5-bd8ffb762113
  cluster:
    host: spark-login.chtc.wisc.edu
    batch: slurm
    squid: null
    scratch: /var/lib/condor/execute/osg01
    ssh:
      key: hosted-ce-chtc-spark-ce1-ssh
      cert: null
      proxyjump: null
      knownHosts: null
  bosco:
    dir: $HOME/bosco-osg-wn-client
    tarball: null
    overrides:
    - name: null
      path: null
    - name: null
      path: null
  pilot:
  - name: standard
    queue: ospool
    limit: 8
    walltime: 4320
    resources:
      cpu: 64
      ram: 248048
      gpu: 0
    vo:
    - osg
    wholeNode: false
    apptainer: false
    os: rhel8
  - name: preempt
    queue: ospool_pre
    limit: 40
    walltime: 4320
    resources:
      cpu: 20
      ram: 122880
      gpu: 0
    vo:
    - osg
    wholeNode: false
    apptainer: false
    os: rhel8
  - name: gpu
    queue: gpu
    limit: 4
    walltime: 4320
    resources:
      cpu: 16
      ram: 126500
      gpu: 1
    vo:
    - osg
    wholeNode: false
    apptainer: false
    os: rhel8
  config: |+
    # CE Specific HTCondor config goes here
