apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: computeentrypoint.osg-htc.org 
spec:
  scope: Namespaced
  group: osg-htc.org
  names:
    kind: ComputeEntrypoint
    plural: computeentrypoints
    singular: computeentrypoint
    shortNames:
      - ce
      - ces
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
        - name: Phase
          type: string
          jsonPath: .status.phase
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            
