---
# kubernetes/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- deployment.yaml

images:
- name: hub.opensciencegrid.org/ashtongraves/ce-controller
  newTag: latest

commonLabels:
  app.kubernetes.io/name: osg-hosted-ce-controller
  app.kubernetes.io/component: controller
  app.kubernetes.io/part-of: osg-hosted-ce